export const SideBarData = {
  title: "PBS Member Portal",
  menulist: [
    {
      hasmenu: true,
      submenu: [
        { img: "/pics/alert-sidebar/1.png", name: "Home" },
        { img: "/pics/alert-sidebar/2.png", name: "Property Overview" },
        { img: "/pics/alert-sidebar/3.png", name: "Building Profiles" },
        { img: "/pics/alert-sidebar/4.png", name: "Calendar" },
        { img: "/pics/alert-sidebar-2.png", name: "DOB" },
        { img: "/pics/alert-sidebar-3.png", name: "ECB" },
        { img: "/pics/alert-sidebar-4.png", name: "FDNY" },
        { img: "/pics/alert-sidebar-5.png", name: "HPD" },
        { img: "/pics/alert-sidebar-6.png", name: "Inspections" },
        { img: "/pics/alert-sidebar-7.png", name: "Permits" },
        { img: "/pics/alert-sidebar-8.png", name: "Support" },
        { img: "/pics/alert-sidebar-9.png", name: "HPD Mailings" },
      ],
      img: "/pics/alert-sidebar-1.png",
      name: "Dashboard",
    },
    {
      hasmenu: true,
      submenu: [
        { img: "/pics/alert-sidebar/5.png", name: "Violations" },
        { img: "/pics/alert-sidebar/6.png", name: "Stop Work/Vacate Orders" },
        { img: "/pics/alert-sidebar/7.png", name: "Complaints" },
        { img: "/pics/alert-sidebar-3.png", name: "ECB" },
        { img: "/pics/alert-sidebar-4.png", name: "FDNY" },
        { img: "/pics/alert-sidebar-5.png", name: "HPD" },
        { img: "/pics/alert-sidebar-6.png", name: "Inspections" },
        { img: "/pics/alert-sidebar-7.png", name: "Permits" },
        { img: "/pics/alert-sidebar-8.png", name: "Support" },
        { img: "/pics/alert-sidebar-9.png", name: "HPD Mailings" },
      ],
      img: "/pics/alert-sidebar-2.png",
      name: "DOB",
    },
    {
      hasmenu: true,
      submenu: [
        { img: "/pics/alert-sidebar-3.png", name: "ECB" },
        { img: "/pics/alert-sidebar-3.png", name: "Violations" },
        { img: "/pics/alert-sidebar-3.png", name: "FDNY Corrections" },
        {
          img: "/pics/alert-sidebar-3.png",
          name: "Penalties",
          hasmenu: true,
          submenu: [
            { img: "/pics/alert-sidebar/15.png", name: "All Panalties" },
            { img: "/pics/alert-sidebar/15.png", name: "Defaulted" },
            { img: "/pics/alert-sidebar/15.png", name: "Imposed" },
            { img: "/pics/alert-sidebar/15.png", name: "Overpaid" },
          ],
        },
        { img: "/pics/alert-sidebar-3.png", name: "Corrections" },
        { img: "/pics/alert-sidebar-3.png", name: "Complaints" },
      ],
      img: "/pics/alert-sidebar-3.png",
      name: "ECB",
    },
    {
      hasmenu: true,
      submenu: [
        { img: "/pics/alert-sidebar-4.png", name: "FDNY" },
        { img: "/pics/alert-sidebar-4.png", name: "FDNY Hearings" },
        { img: "/pics/alert-sidebar-4.png", name: "FDNY Corrections" },
        {
          img: "/pics/alert-sidebar-4.png",
          name: "Penalties",
          hasmenu: true,
          submenu: [
            { img: "/pics/alert-sidebar-4.png", name: "All Penalties" },
            { img: "/pics/alert-sidebar-4.png", name: "Defaulted" },
            { img: "/pics/alert-sidebar-4.png", name: "Imposed" },
            { img: "/pics/alert-sidebar-4.png", name: "Overpaid" },
          ],
        },
        { img: "/pics/alert-sidebar-4.png", name: "Corrections" },
        { img: "/pics/alert-sidebar-4.png", name: "Complaints" },
      ],
      img: "/pics/alert-sidebar-4.png",
      name: "FDNY",
    },
    {
      hasmenu: true,
      submenu: [
        { img: "/pics/alert-sidebar-5.png", name: "HPD" },
        { img: "/pics/alert-sidebar-5.png", name: "Elevator" },
        { img: "/pics/alert-sidebar-5.png", name: "FDNY Account" },
        { img: "/pics/alert-sidebar-5.png", name: "Permits" },
        { img: "/pics/alert-sidebar-5.png", name: "Support" },
        { img: "/pics/alert-sidebar-5.png", name: "HPD Mailings" },
      ],
      img: "/pics/alert-sidebar-5.png",
      name: "HPD",
    },
    {
      hasmenu: true,
      submenu: [
        { img: "/pics/alert-sidebar-6.png", name: "DOB" },
        { img: "/pics/alert-sidebar-6.png", name: "ECB" },
        { img: "/pics/alert-sidebar-6.png", name: "FDNY" },
        { img: "/pics/alert-sidebar-6.png", name: "HPD" },
        { img: "/pics/alert-sidebar-6.png", name: "DEP" },
        { img: "/pics/alert-sidebar-6.png", name: "Facade" },
        { img: "/pics/alert-sidebar-6.png", name: "Others" },
        { img: "/pics/alert-sidebar-6.png", name: "Litigations" },
        { img: "/pics/alert-sidebar-6.png", name: "Registrations" },
        { img: "/pics/alert-sidebar-6.png", name: "Repairs" },
        { img: "/pics/alert-sidebar-6.png", name: "Inspections" },
        { img: "/pics/alert-sidebar-6.png", name: "Permits" },
        { img: "/pics/alert-sidebar-6.png", name: "Support" },
        { img: "/pics/alert-sidebar-6.png", name: "HPD Mailings" },
      ],
      img: "/pics/alert-sidebar-6.png",
      name: "Inspections",
    },
    {
      hasmenu: true,
      submenu: [
        {
          img: "/pics/alert-sidebar-7.png",
          name: "DOB",
          hasmenu: true,
          submenu: [
            { img: "/pics/alert-sidebar/15.png", name: "DOB Permits" },
            { img: "/pics/alert-sidebar/15.png", name: "DOB NOW Permits" },
            { img: "/pics/alert-sidebar/15.png", name: "DOB Elev. Permits" },
          ],
        },
        { img: "/pics/alert-sidebar-7.png", name: "DOB AHV" },
        { img: "/pics/alert-sidebar-7.png", name: "DOB Permits" },
        { img: "/pics/alert-sidebar-7.png", name: "DOB NOW Permits" },
        { img: "/pics/alert-sidebar-7.png", name: "DOB ELE. Permits" },
        { img: "/pics/alert-sidebar-7.png", name: "DOB AHV" },
        { img: "/pics/alert-sidebar-7.png", name: "FDNY Account" },
        { img: "/pics/alert-sidebar-7.png", name: "Elevator" },
        {
          img: "/pics/alert-sidebar-7.png",
          name: "Open Applications",
          hasmenu: true,
          submenu: [
            { img: "/pics/alert-sidebar/15.png", name: "DOB Job Fil." },
            { img: "/pics/alert-sidebar/15.png", name: "DOB NOW Job Fil." },
            { img: "/pics/alert-sidebar/15.png", name: "BSA Applications" },
          ],
        },
        { img: "/pics/alert-sidebar-7.png", name: "Support" },
        { img: "/pics/alert-sidebar-7.png", name: "HPD Mailings" },
      ],
      img: "/pics/alert-sidebar-7.png",
      name: "Permits",
    },
    { hasmenu: false, img: "/pics/alert-sidebar-8.png", name: "Support" },
    {
      hasmenu: false,
      img: "/pics/alert-sidebar-9.png",
      name: "HPD Mailings",
    },
  ],
};
